version: '3.9'

services:

  db:
    image: postgres:15-alpine
    container_name: dynamic_form_db
    restart: unless-stopped
    environment:
      POSTGRES_DB:       dynamic_form_db
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d dynamic_form_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dynamic_form_web
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
